import type { ProviderTemplate } from '../types';

export const PROVIDER_TEMPLATES: ProviderTemplate[] = [
  {
    type: 'openai',
    label: 'OpenAI',
    defaultBaseUrl: 'https://api.openai.com/v1',
    defaultModel: 'gpt-4o',
    modelOptions: ['gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo', 'gpt-4', 'gpt-3.5-turbo', 'o1', 'o1-mini', 'o3-mini'],
    requiresApiKey: true,
    docsUrl: 'https://platform.openai.com/docs',
    description: 'OpenAI GPT models including GPT-4o, o1, and more.',
    color: '#10a37f',
  },
  {
    type: 'anthropic',
    label: 'Claude (Anthropic)',
    defaultBaseUrl: 'https://api.anthropic.com',
    defaultModel: 'claude-opus-4-5',
    modelOptions: [
      'claude-opus-4-5',
      'claude-sonnet-4-5',
      'claude-haiku-4-5',
      'claude-opus-4',
      'claude-3-7-sonnet-20250219',
      'claude-3-5-sonnet-20241022',
      'claude-3-5-haiku-20241022',
      'claude-3-opus-20240229',
    ],
    requiresApiKey: true,
    docsUrl: 'https://docs.anthropic.com',
    description: 'Anthropic\'s Claude models – intelligent and safe AI assistants.',
    color: '#d4a853',
  },
  {
    type: 'gemini',
    label: 'Google Gemini',
    defaultBaseUrl: 'https://generativelanguage.googleapis.com',
    defaultModel: 'gemini-2.0-flash',
    modelOptions: [
      'gemini-2.5-pro-preview-06-05',
      'gemini-2.0-flash',
      'gemini-2.0-flash-lite',
      'gemini-1.5-pro',
      'gemini-1.5-flash',
      'gemini-1.5-flash-8b',
    ],
    requiresApiKey: true,
    docsUrl: 'https://ai.google.dev/docs',
    description: 'Google\'s Gemini multimodal AI models.',
    color: '#4285f4',
  },
  {
    type: 'perplexity',
    label: 'Perplexity',
    defaultBaseUrl: 'https://api.perplexity.ai',
    defaultModel: 'llama-3.1-sonar-large-128k-online',
    modelOptions: [
      'llama-3.1-sonar-large-128k-online',
      'llama-3.1-sonar-small-128k-online',
      'llama-3.1-sonar-huge-128k-online',
      'llama-3.1-sonar-large-128k-chat',
      'llama-3.1-sonar-small-128k-chat',
    ],
    requiresApiKey: true,
    docsUrl: 'https://docs.perplexity.ai',
    description: 'Perplexity AI – real-time search-augmented language models.',
    color: '#20b8cd',
  },
  {
    type: 'ollama',
    label: 'Ollama (Local)',
    defaultBaseUrl: 'http://localhost:11434',
    defaultModel: 'llama3.2',
    modelOptions: [
      'llama3.2',
      'llama3.1',
      'mistral',
      'mixtral',
      'codellama',
      'phi3',
      'gemma2',
      'deepseek-r1',
      'qwen2.5',
    ],
    requiresApiKey: false,
    docsUrl: 'https://ollama.com',
    description: 'Run AI models locally on your machine with Ollama.',
    color: '#e84393',
  },
  {
    type: 'openrouter',
    label: 'OpenRouter',
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    defaultModel: 'openai/gpt-4o',
    modelOptions: [
      'openai/gpt-4o',
      'anthropic/claude-opus-4-5',
      'google/gemini-2.0-flash-001',
      'meta-llama/llama-3.3-70b-instruct',
      'mistralai/mistral-large',
      'deepseek/deepseek-r1',
      'x-ai/grok-beta',
    ],
    requiresApiKey: true,
    docsUrl: 'https://openrouter.ai/docs',
    description: 'Unified API access to hundreds of AI models from all providers.',
    color: '#7c3aed',
  },
  {
    type: 'custom',
    label: 'Custom / OpenAI-Compatible',
    defaultBaseUrl: 'http://localhost:8080/v1',
    defaultModel: 'default',
    modelOptions: ['default'],
    requiresApiKey: false,
    docsUrl: '',
    description: 'Any OpenAI-compatible API endpoint (LM Studio, vLLM, etc.).',
    color: '#6b7280',
  },
];

export const getProviderTemplate = (type: string): ProviderTemplate | undefined =>
  PROVIDER_TEMPLATES.find((t) => t.type === type);
